<?php

namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class QuestionsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        DB::table('questions')->delete();
        
        DB::table('questions')->insert(array (
            0 => 
            array (
                'id' => 1,
                'code' => 'A',
                'content' => 'Apakah anda berniat mengusulkan atas nama lembaga desa/kelurahan?',
                'is_HA' => false,
                'is_HD' => true,
                'is_HKm' => false,
                'is_HTR' => false,
                'is_KK' => false,
                'status' => 'inactive',
                'created_by' => 'system',
                'modified_by' => 'system',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'prerequisite' => NULL,
                'category' => NULL,
                'order' => NULL,
                'legal_reference' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'code' => 'B',
                'content' => 'Apakah areal anda berada di dalam satu kesatuan lansekap/bentang alam/bentang lahan?',
                'is_HA' => false,
                'is_HD' => true,
                'is_HKm' => false,
                'is_HTR' => true,
                'is_KK' => false,
                'status' => 'inactive',
                'created_by' => 'system',
                'modified_by' => 'system',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'prerequisite' => NULL,
                'category' => NULL,
                'order' => NULL,
                'legal_reference' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'code' => 'C',
                'content' => 'Apakah areal yang anda usulkan berada di dalam wilayah desa anda atau areal hasil kesepakatan batas pengelolaan antara desa yang berdampingan dengan desa anda?',
                'is_HA' => false,
                'is_HD' => true,
                'is_HKm' => false,
                'is_HTR' => false,
                'is_KK' => false,
                'status' => 'inactive',
                'created_by' => 'system',
                'modified_by' => 'system',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'prerequisite' => NULL,
                'category' => NULL,
                'order' => NULL,
                'legal_reference' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'code' => 'D',
                'content' => 'Apakah areal yang anda usulkan berupa areal Gambut?',
                'is_HA' => false,
                'is_HD' => false,
                'is_HKm' => false,
                'is_HTR' => true,
                'is_KK' => false,
                'status' => 'inactive',
                'created_by' => 'system',
                'modified_by' => 'system',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'prerequisite' => NULL,
                'category' => NULL,
                'order' => NULL,
                'legal_reference' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'code' => 'E',
                'content' => 'Apakah areal yang anda usulkan dapat dikatakan sebagai areal yang tidak produktif dengan tutupan lahan rendah sampai sedang?',
                'is_HA' => false,
                'is_HD' => false,
                'is_HKm' => false,
                'is_HTR' => true,
                'is_KK' => false,
                'status' => 'inactive',
                'created_by' => 'system',
                'modified_by' => 'system',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'prerequisite' => NULL,
                'category' => NULL,
                'order' => NULL,
                'legal_reference' => NULL,
            ),
            5 => 
            array (
                'id' => 6,
                'code' => 'F',
                'content' => 'Apakah areal yang anda usulkan memiliki potensi menjadi sumber penghidupan masyarakat setempat atau areal konflik atau berpotensi konflik?',
                'is_HA' => false,
                'is_HD' => false,
                'is_HKm' => false,
                'is_HTR' => false,
                'is_KK' => true,
                'status' => 'inactive',
                'created_by' => 'system',
                'modified_by' => 'system',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'prerequisite' => NULL,
                'category' => NULL,
                'order' => NULL,
                'legal_reference' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'code' => 'G',
                'content' => 'Apakah areal yang anda usulkan sudah dimanfaatkan oleh warga setempat?',
                'is_HA' => false,
                'is_HD' => true,
                'is_HKm' => true,
                'is_HTR' => false,
                'is_KK' => false,
                'status' => 'inactive',
                'created_by' => 'system',
                'modified_by' => 'system',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'prerequisite' => NULL,
                'category' => NULL,
                'order' => NULL,
                'legal_reference' => NULL,
            ),
            7 => 
            array (
                'id' => 8,
                'code' => 'H',
                'content' => 'Apakah calon areal yang akan anda usulkan berada di dalam wilayah persetujuan penggunaan kawasan hutan?',
                'is_HA' => false,
                'is_HD' => false,
                'is_HKm' => false,
                'is_HTR' => false,
                'is_KK' => true,
                'status' => 'inactive',
                'created_by' => 'system',
                'modified_by' => 'system',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'prerequisite' => NULL,
                'category' => NULL,
                'order' => NULL,
                'legal_reference' => NULL,
            ),
            8 => 
            array (
                'id' => 9,
                'code' => 'I',
                'content' => 'Apakah calon areal yang ditanami sawit tersebut sudah dilekola oleh pengelola yang telah tinggal di dalam dan/atau sekitar kawasan tersebut selama minimal 5 tahun secara terus menerus?',
                'is_HA' => false,
                'is_HD' => true,
                'is_HKm' => true,
                'is_HTR' => false,
                'is_KK' => true,
                'status' => 'inactive',
                'created_by' => 'system',
                'modified_by' => 'system',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'prerequisite' => NULL,
                'category' => NULL,
                'order' => NULL,
                'legal_reference' => NULL,
            ),
            9 => 
            array (
                'id' => 10,
                'code' => 'J',
                'content' => 'Apakah di areal yang anda usulkan terdapat tegakan berupa sawit?',
                'is_HA' => false,
                'is_HD' => true,
                'is_HKm' => true,
                'is_HTR' => false,
                'is_KK' => true,
                'status' => 'inactive',
                'created_by' => 'system',
                'modified_by' => 'system',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'prerequisite' => NULL,
                'category' => NULL,
                'order' => NULL,
                'legal_reference' => NULL,
            ),
            10 => 
            array (
                'id' => 11,
                'code' => 'K',
                'content' => 'Apakah MHA tersebut tinggal di dalam kawasan hutan atau areal yang akan diusulkan, serta telah lama memanfaatkannya?',
                'is_HA' => true,
                'is_HD' => false,
                'is_HKm' => false,
                'is_HTR' => false,
                'is_KK' => false,
                'status' => 'inactive',
                'created_by' => 'system',
                'modified_by' => 'system',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'prerequisite' => NULL,
                'category' => NULL,
                'order' => NULL,
                'legal_reference' => NULL,
            ),
            11 => 
            array (
                'id' => 12,
                'code' => 'L',
                'content' => 'Apakah pembentukan lembaga desa/kelurahan tersebut melalui Peraturan Desa atau Peraturan Bupati/Walikota?',
                'is_HA' => false,
                'is_HD' => true,
                'is_HKm' => false,
                'is_HTR' => false,
                'is_KK' => false,
                'status' => 'inactive',
                'created_by' => 'system',
                'modified_by' => 'system',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'prerequisite' => NULL,
                'category' => NULL,
                'order' => NULL,
                'legal_reference' => NULL,
            ),
            12 => 
            array (
                'id' => 13,
                'code' => 'M',
            'content' => 'Apakah sudah ada MHA (Masayarakat Hukum Adat) yang ditetapkan dengan Perda (jika MHA berada di dalam kawasan hutan negara) atau Perda atau Keputusan Gub.dan/atau Bupati/wali kota (jika MHA di luar kawasan hutan)?',
                'is_HA' => true,
                'is_HD' => false,
                'is_HKm' => false,
                'is_HTR' => false,
                'is_KK' => false,
                'status' => 'inactive',
                'created_by' => 'system',
                'modified_by' => 'system',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'prerequisite' => NULL,
                'category' => NULL,
                'order' => NULL,
                'legal_reference' => NULL,
            ),
            13 => 
            array (
                'id' => 14,
                'code' => 'N',
            'content' => 'Apakah areal yang anda usulkan berada di dalam kawasan konservasi (misal: taman nasional)?',
                'is_HA' => false,
                'is_HD' => true,
                'is_HKm' => true,
                'is_HTR' => true,
                'is_KK' => true,
                'status' => 'inactive',
                'created_by' => 'system',
                'modified_by' => 'system',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'prerequisite' => NULL,
                'category' => NULL,
                'order' => NULL,
                'legal_reference' => NULL,
            ),
            14 => 
            array (
                'id' => 15,
                'code' => 'O',
            'content' => 'Apakah areal yang anda usulkan berada di dalam kawasan perusahan kehutanan (HTI/Hutan Tanaman Industri)?',
                'is_HA' => false,
                'is_HD' => true,
                'is_HKm' => true,
                'is_HTR' => true,
                'is_KK' => true,
                'status' => 'inactive',
                'created_by' => 'system',
                'modified_by' => 'system',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'prerequisite' => NULL,
                'category' => NULL,
                'order' => NULL,
                'legal_reference' => NULL,
            ),
            15 => 
            array (
                'id' => 19,
                'code' => 'D',
                'content' => 'Apakah pembentukan lembaga desa/kelurahan tersebut melalui Peraturan Desa atau Peraturan Bupati/Walikota?',
                'is_HA' => false,
                'is_HD' => true,
                'is_HKm' => false,
                'is_HTR' => false,
                'is_KK' => false,
                'status' => 'active',
                'created_by' => 'system',
                'modified_by' => 'system',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'prerequisite' => '{"C":"Tidak"}',
                'category' => 'Kelembagaan',
                'order' => 4,
            'legal_reference' => 'Permen LHK No.9/2021 (Pasal 12) dan Buku Saku Fasilitasi Permohonan Perhutanan Sosial',
            ),
            16 => 
            array (
                'id' => 25,
                'code' => 'J',
            'content' => 'Apakah areal yang Anda usulkan merupakan areal konflik atau berpotensi konflik? (Persoalan masalah pemanfaatan, baik tumpang tindih lahan atau perbedaan hak akses pemanfaatan)',
                'is_HA' => false,
                'is_HD' => false,
                'is_HKm' => false,
                'is_HTR' => false,
                'is_KK' => true,
                'status' => 'active',
                'created_by' => 'system',
                'modified_by' => 'system',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'prerequisite' => '{}',
                'category' => 'Potensi Masalah Sosial',
                'order' => 10,
            'legal_reference' => 'Permen LHK No.9/2021 (Pasal 45) dan Buku Saku Fasilitasi Permohonan Perhutanan Sosial',
            ),
            17 => 
            array (
                'id' => 16,
                'code' => 'A',
                'content' => 'Apakah areal yang Anda usulkan berada di dalam wilayah desa Anda?',
                'is_HA' => false,
                'is_HD' => true,
                'is_HKm' => false,
                'is_HTR' => false,
                'is_KK' => false,
                'status' => 'active',
                'created_by' => 'system',
                'modified_by' => 'system',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'prerequisite' => '{}',
                'category' => 'Status Kawasan',
                'order' => 1,
            'legal_reference' => 'Permen LHK No.9/2021 (Pasal 11) dan Buku Saku Fasilitasi Permohonan Perhutanan Sosial',
            ),
            18 => 
            array (
                'id' => 17,
                'code' => 'B',
                'content' => 'Apakah areal yang Anda usulkan merupakan areal hasil kesepakatan batas pengelolaan antara desa yang berdampingan dengan desa Anda?',
                'is_HA' => false,
                'is_HD' => true,
                'is_HKm' => false,
                'is_HTR' => false,
                'is_KK' => false,
                'status' => 'active',
                'created_by' => 'system',
                'modified_by' => 'system',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'prerequisite' => '{"A":"Ya"}',
                'category' => 'Status Kawasan',
                'order' => 2,
            'legal_reference' => 'Permen LHK No.9/2021 (Pasal 11) dan Buku Saku Fasilitasi Permohonan Perhutanan Sosial',
            ),
            19 => 
            array (
                'id' => 18,
                'code' => 'C',
                'content' => 'Apakah Anda berniat mengusulkan atas nama lembaga desa/kelurahan?',
                'is_HA' => false,
                'is_HD' => true,
                'is_HKm' => false,
                'is_HTR' => false,
                'is_KK' => false,
                'status' => 'active',
                'created_by' => 'system',
                'modified_by' => 'system',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'prerequisite' => '{"A":"Tidak","B":"Tidak"}',
                'category' => 'Kelembagaan',
                'order' => 3,
            'legal_reference' => 'Permen LHK No.9/2021 (Pasal 12) dan Buku Saku Fasilitasi Permohonan Perhutanan Sosial',
            ),
            20 => 
            array (
                'id' => 20,
                'code' => 'E',
                'content' => 'Apakah areal yang Anda usulkan berupa areal Gambut?',
                'is_HA' => false,
                'is_HD' => true,
                'is_HKm' => true,
                'is_HTR' => true,
                'is_KK' => true,
                'status' => 'active',
                'created_by' => 'system',
                'modified_by' => 'system',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'prerequisite' => '{}',
                'category' => 'Biofisik',
                'order' => 5,
            'legal_reference' => 'Permen LHK No.9/2021 (Pasal 174) dan Buku Saku Fasilitasi Permohonan Perhutanan Sosial',
            ),
            21 => 
            array (
                'id' => 23,
                'code' => 'H',
                'content' => 'Apakah calon areal yang akan Anda usulkan berada di dalam wilayah persetujuan penggunaan kawasan hutan?',
                'is_HA' => false,
                'is_HD' => true,
                'is_HKm' => true,
                'is_HTR' => true,
                'is_KK' => true,
                'status' => 'active',
                'created_by' => 'system',
                'modified_by' => 'system',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'prerequisite' => '{"G":"Ya"}',
                'category' => 'Status Kawasan',
                'order' => 8,
            'legal_reference' => 'Permen LHK No.9/2021 (Pasal 22, 44 & 45) dan Buku Saku Fasilitasi Permohonan Perhutanan Sosial',
            ),
            22 => 
            array (
                'id' => 22,
                'code' => 'G',
            'content' => 'Apakah areal yang Anda usulkan berada di dalam kawasan perusahan kehutanan (HTI/Hutan Tanaman Industri)?',
                'is_HA' => false,
                'is_HD' => true,
                'is_HKm' => true,
                'is_HTR' => true,
                'is_KK' => true,
                'status' => 'active',
                'created_by' => 'system',
                'modified_by' => 'system',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'prerequisite' => '{}',
                'category' => 'Status Kawasan',
                'order' => 7,
            'legal_reference' => 'Permen LHK No.9/2021 (Pasal 22, 44, & 45) dan Buku Saku Fasilitasi Permohonan Perhutanan Sosial',
            ),
            23 => 
            array (
                'id' => 21,
                'code' => 'F',
                'content' => 'Apakah areal yang Anda usulkan dapat dikatakan sebagai areal yang tidak produktif dengan tutupan lahan rendah sampai sedang?',
                'is_HA' => false,
                'is_HD' => false,
                'is_HKm' => false,
                'is_HTR' => true,
                'is_KK' => false,
                'status' => 'active',
                'created_by' => 'system',
                'modified_by' => 'system',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'prerequisite' => '{}',
                'category' => 'Biofisik',
                'order' => 6,
            'legal_reference' => 'Permen LHK No.9/2021 (Pasal 34) dan Buku Saku Fasilitasi Permohonan Perhutanan Sosial',
            ),
            24 => 
            array (
                'id' => 24,
                'code' => 'I',
                'content' => 'Apakah areal yang Anda usulkan memiliki potensi menjadi sumber penghidupan masyarakat setempat?',
                'is_HA' => false,
                'is_HD' => false,
                'is_HKm' => false,
                'is_HTR' => false,
                'is_KK' => true,
                'status' => 'active',
                'created_by' => 'system',
                'modified_by' => 'system',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'prerequisite' => '{}',
                'category' => 'Pemanfaatan',
                'order' => 9,
            'legal_reference' => 'Permen LHK No.9/2021 (Pasal 45) dan Buku Saku Fasilitasi Permohonan Perhutanan Sosial',
            ),
            25 => 
            array (
                'id' => 26,
                'code' => 'K',
            'content' => 'Apakah sudah ada MHA (Masyarakat Hukum Adat) yang ditetapkan dengan Perda (jika MHA berada di dalam kawasan hutan negara), atau Perda atau Keputusan Gubernur dan/atau Bupati/Walikota (jika MHA di luar kawasan hutan)?',
                'is_HA' => true,
                'is_HD' => false,
                'is_HKm' => false,
                'is_HTR' => false,
                'is_KK' => false,
                'status' => 'active',
                'created_by' => 'system',
                'modified_by' => 'system',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'prerequisite' => '{}',
                'category' => 'Kelembagaan',
                'order' => 11,
            'legal_reference' => 'Permen LHK No.9/2021 (Pasal 63)',
            ),
            26 => 
            array (
                'id' => 31,
                'code' => 'P',
                'content' => 'Apakah calon areal yang ditanami sawit tersebut sudah dilekola oleh pengelola yang telah tinggal di dalam dan/atau sekitar kawasan tersebut selama minimal 5 tahun secara terus menerus?',
                'is_HA' => false,
                'is_HD' => true,
                'is_HKm' => true,
                'is_HTR' => false,
                'is_KK' => true,
                'status' => 'inactive',
                'created_by' => 'system',
                'modified_by' => 'system',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'prerequisite' => '{"O":"Tidak"}',
                'category' => 'Pemanfaatan',
                'order' => 16,
            'legal_reference' => 'Permen LHK No.9/2021 (Pasal 11, 22, & 45) dan Buku Saku Fasilitasi Permohonan Perhutanan Sosial',
            ),
            27 => 
            array (
                'id' => 28,
                'code' => 'M',
                'content' => 'Apakah areal yang Anda usulkan berada di dalam satu kesatuan lansekap/bentang alam/bentang lahan?',
                'is_HA' => false,
                'is_HD' => true,
                'is_HKm' => true,
                'is_HTR' => true,
                'is_KK' => true,
                'status' => 'active',
                'created_by' => 'system',
                'modified_by' => 'system',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'prerequisite' => '{}',
                'category' => 'Status Kawasan',
                'order' => 13,
            'legal_reference' => 'Permen LHK No.9/2021 (Pasal 11 & 34) dan Buku Saku Fasilitasi Permohonan Perhutanan Sosial',
            ),
            28 => 
            array (
                'id' => 29,
                'code' => 'N',
                'content' => 'Apakah areal yang Anda usulkan sudah dimanfaatkan oleh warga setempat?',
                'is_HA' => false,
                'is_HD' => true,
                'is_HKm' => true,
                'is_HTR' => true,
                'is_KK' => true,
                'status' => 'active',
                'created_by' => 'system',
                'modified_by' => 'system',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'prerequisite' => '{}',
                'category' => 'Pemanfaatan',
                'order' => 14,
            'legal_reference' => 'Permen LHK No.9/2021 (Pasal 11 & 22) dan Buku Saku Fasilitasi Permohonan Perhutanan Sosial',
            ),
            29 => 
            array (
                'id' => 30,
                'code' => 'O',
            'content' => 'Apakah di areal yang Anda usulkan terdapat tegakan berupa sawit, dan sudah dikelola oleh masyarakat (perseorangan) yang telah tinggal di dalam dan/atau sekitar kawasan tersebut selama minimal 5 tahun secara terus menerus?',
                'is_HA' => false,
                'is_HD' => true,
                'is_HKm' => true,
                'is_HTR' => true,
                'is_KK' => true,
                'status' => 'active',
                'created_by' => 'system',
                'modified_by' => 'system',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'prerequisite' => '{}',
                'category' => 'Pemanfaatan',
                'order' => 15,
            'legal_reference' => 'Permen LHK No.9/2021 (Pasal 11, 22, & 45) dan Buku Saku Fasilitasi Permohonan Perhutanan Sosial',
            ),
            30 => 
            array (
                'id' => 27,
                'code' => 'L',
                'content' => 'Apakah MHA tersebut tinggal di dalam kawasan hutan atau areal yang akan diusulkan, serta telah lama memanfaatkannya?',
                'is_HA' => true,
                'is_HD' => false,
                'is_HKm' => false,
                'is_HTR' => false,
                'is_KK' => false,
                'status' => 'active',
                'created_by' => 'system',
                'modified_by' => 'system',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'prerequisite' => '{"K":"Tidak"}',
                'category' => 'Kelembagaan',
                'order' => 12,
            'legal_reference' => 'Permen LHK No.9/2021 (Pasal 62 & 63)',
            ),
        ));
        
        
    }
}